CREATE TABLE public.USUARIO (
  ID SERIAL NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(50),
  URL_FOTO VARCHAR(100),
  NUM_VERSAO_REGISTRO INTEGER NOT NULL,
  CONSTRAINT USUARIO_PK PRIMARY KEY (ID),
  CONSTRAINT USUARIO_UK UNIQUE (LOGIN)
);