CREATE TABLE public.USUARIO (
  ID SERIAL NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(50),
  NUM_VERSAO_REGISTRO INTEGER NOT NULL
);

ALTER TABLE ONLY public.USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID);
ALTER TABLE ONLY public.USUARIO ADD CONSTRAINT USUARIO_UK UNIQUE (LOGIN);