CREATE TABLE public.DISPOSITIVO (
  ID SERIAL NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  NUM_REGISTRO VARCHAR(100) NOT NULL,
  IND_OS VARCHAR(20) NOT NULL,
  IND_SISTEMA VARCHAR(20) NOT NULL,
  DTHORA_CADASTRO TIMESTAMP,
  DTHORA_EXCLUSAO TIMESTAMP,
  NUM_VERSAO_REGISTRO INTEGER NOT NULL
);

ALTER TABLE ONLY public.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_PK PRIMARY KEY (ID);
ALTER TABLE ONLY public.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_UK UNIQUE (NUM_REGISTRO, IND_OS, IND_SISTEMA);
ALTER TABLE ONLY public.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_FK FOREIGN KEY (ID_USUARIO) REFERENCES public.USUARIO(id) ON DELETE CASCADE;