CREATE TABLE public.DISPOSITIVO (
  ID SERIAL NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  NUM_REGISTRO VARCHAR(100) NOT NULL,
  IND_OS VARCHAR(20) NOT NULL,
  IND_SISTEMA VARCHAR(20) NOT NULL,
  DTHORA_CADASTRO TIMESTAMP NOT NULL,
  DTHORA_EXCLUSAO TIMESTAMP,
  NUM_VERSAO_REGISTRO INTEGER NOT NULL,
  CONSTRAINT DISPOSITIVO_PK PRIMARY KEY (ID),
  CONSTRAINT DISPOSITIVO_UK UNIQUE (NUM_REGISTRO, IND_OS, IND_SISTEMA),
  CONSTRAINT DISPOSITIVO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);